//
//  OpenAiResponse.swift
//  Sentia
//
//  Created by Rafael Rezende Machado on 06/07/25.
//

import Foundation

/// A model representing the response structure returned by the OpenAI Chat Completions API.
///
/// This structure decodes only the relevant portion of the API response:
/// an array of `choices`, each containing a `message` with a `role` and `content`.
///
/// Example JSON:
/// ```json
/// {
///   "choices": [
///     {
///       "message": {
///         "role": "assistant",
///         "content": "This is a response"
///       }
///     }
///   ]
/// }
/// ```
struct OpenAIResponse: Decodable {

    /// The array of generated completions from the model.
    let choices: [Choice]

    /// Represents a single choice in the response.
    struct Choice: Decodable {
        /// The message object containing the role and text content.
        let message: Message
    }

    /// Represents a chat message returned by the assistant.
    struct Message: Decodable {
        /// The role of the message author (e.g., "assistant", "user", or "system").
        let role: String

        /// The textual content generated by the assistant.
        let content: String?
    }
}
